# Generated by Django 5.2.5 on 2025-09-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.FloatField(help_text='Puissance instantanée en watts (W)')),
                ('voltage', models.FloatField(help_text='Tension en volts (V)')),
                ('current', models.FloatField(help_text='Courant en ampères (A)')),
                ('energy', models.FloatField(help_text='Énergie consommée en watt-heures (Wh)')),
                ('timestamp', models.DateTimeField(help_text='Horodatage ISO 8601')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
